spring.application.name=sunhom-backend

# ===============================
# DATABASE
# ===============================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# ===============================
# FLYWAY
# ===============================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# ===============================
# REDIS (IMPORTANT FIX)
# ===============================
spring.cache.type=redis
spring.data.redis.host=${REDIS_HOST:redis}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.timeout=60000

spring.cache.redis.time-to-live=1800000
spring.cache.redis.cache-null-values=false

# ===============================
# JWT Configuration
# ===============================
security.jwt.secret=${JWT_SECRET}
security.jwt.issuer=${JWT_ISSUER}
security.jwt.access-token-expiry=1800

# ===============================
# SERVER
# ===============================
server.port=${PORT:8080}

# ===============================
# CLOUDINARY
# ===============================
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}
# ===============================
# EMAIL (HOSTINGER SMTP)
# ===============================

spring.mail.host=smtp.hostinger.com
spring.mail.port=587
spring.mail.username=info@sunhom.in
spring.mail.password=sunhom$0326

spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000